%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/.../testing_filter/temp_data_1.txt
%
% Auto-generated by MATLAB on 07-Apr-2022 16:43:07

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Temperature_Sensor_1", "Second_Sensor_1"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
temp_sensor_1_data_march27 = readtable("/Users/.../testing_filter/temp_data_1.txt", opts);


%% Clear temporary variables
clear opts