%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/.../Last test/time_sec.txt
%
% Auto-generated by MATLAB on 20-Apr-2022 12:00:05

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "time";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
time_sec = readtable("/Users/.../Last test/time_sec.txt", opts);
time_30_sec = readtable("/Users/.../Last test/time_30_sec.txt", opts);


%% Clear temporary variables
clear opts