%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/.../Last test/sent_ESP_data_1.txt
%
% Auto-generated by MATLAB on 20-Apr-2022 11:49:06

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "data";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
sent_sensor_1 = readtable("/Users/.../Last test/sent_ESP_data_1.txt", opts);
sent_sensor_2 = readtable("/Users/.../Last test/sent_ESP_data_2.txt", opts);
sent_sensor_6 = readtable("/Users/.../Last test/sent_ESP_data_6.txt", opts);


%% Clear temporary variables
clear opts