%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/.../Dual_test/No Heater Test/temp_data_1.txt
%
% Auto-generated by MATLAB on 20-Apr-2022 12:02:28

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "Temperature";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
temp_data_1 = readtable("/Users/.../Dual_test/Tss/temp_data_1.txt", opts);
temp_data_2 = readtable("/Users/.../Dual_test/Tss/temp_data_2.txt", opts);
temp_data_3 = readtable("/Users/.../Dual_test/Tss/temp_data_3.txt", opts);
temp_data_4 = readtable("/Users/.../Dual_test/Tss/temp_data_4.txt", opts);
temp_data_5 = readtable("/Users/.../Dual_test/Tss/temp_data_5.txt", opts);
temp_data_6 = readtable("/Users/.../Dual_test/Tss/temp_data_6.txt", opts);


%% Clear temporary variables
clear opts