%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/.../Singular_test/time_sample_2.txt
%
% Auto-generated by MATLAB on 15-Apr-2022 17:04:26

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "time_sec";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
time_sample = readtable("/Users/.../Singular_test/1st/time_sample_2.txt", opts);


%% Clear temporary variables
clear opts