%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/.../Singular_test/temp_data_1.txt
%
% Auto-generated by MATLAB on 15-Apr-2022 16:37:53

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "Temperature";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
temp_data_1 = readtable("/Users/.../Singular_test/1st/temp_data_1.txt", opts);
temp_data_2 = readtable("/Users/.../Singular_test/1st/temp_data_2.txt", opts);
temp_data_3 = readtable("/Users/.../Singular_test/1st/temp_data_3.txt", opts);

%% Clear temporary variables
clear opts