%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/.../Singular_test/sent_ESP_data_1.txt
%
% Auto-generated by MATLAB on 15-Apr-2022 17:21:36

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "ESP";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
sent_data_1 = readtable("/Users/.../Singular_test/1st/sent_ESP_data_1.txt", opts);
sent_data_2 = readtable("/Users/.../Singular_test/1st/sent_ESP_data_2.txt", opts);
sent_data_3 = readtable("/Users/.../Singular_test/1st/sent_ESP_data_3.txt", opts);


%% Clear temporary variables
clear opts